### ISSUE TITLE
Huggingface dataset is missing

### ISSUE THREAD

**Issue by vishaal27** [ugorsahin/Generative-Negative-Mining#1]
Hey, thanks for your great work and congratulations on your work's acceptance to WACV!

I tried to access the dataset on huggingface, but it seems to be broken: https://huggingface.co/datasets/ugursahin/Generative-Negative-Mining-Dataset

Could you please check and let me know when I can access it? 

Thanks!

**Comment by ugorsahin** [comment]
Hey,

Thank you for notifying me, I missed that issue somehow. Yes the link is broken, please refer to : https://huggingface.co/datasets/ugursahin/generative-negative-mining-dataset . The test split is uploaded and you can find the training dataset in following days.

**Comment by vishaal27** [comment]
Great, thanks!

**Comment by ugorsahin** [comment]
Hey Vishaal,

I uploaded the training annotation file and training images. Let me know if you have any issues.

**Comment by vishaal27** [comment]
Awesome, thanks I can see it! :)
